#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "OceanicNext"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    vim_help_language = "cn"
    # options for layers checkers
    enable_neomake = true
    enable_ale = false
    lint_on_the_fly = false

    # option for autocomplete
    autocomplete_method = "coc"
    # bootstrap configuration
    filemanager = "nerdtree" 

    
# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "lang#rust"
[[layers]]
name='long#c'
enable_clang_syntax_highlight = true
[[layers]]
name = "lang#markdown"
[[layers]]
name = "lang#cmake"
[[layers]]
name = "chinese"
[[layers]]
name = "lsp"
filetypes = [
    "rust",
    "c",
    "cpp"
  ]
[layers.override_cmd]
    rust = ["rls"]
    c = ["clangd"]   

[[layers]]
  name = "format"

[[custom_plugins]]
  repo = "mhartington/oceanic-next"
  merged = 0 

[[layers]]
  name = 'checkers'

[[layers]]
  name = "tools#dash"
